<?php

/**
 * Implementation of hook_init().
 */
function jsonify_init() {
  drupal_add_js(drupal_get_path('module', 'jsonify') . '/jsonify.js');
}

/**
 * Implementation of hook_menu().
 */
function jsonify_menu() {
  $items = array();
  
  $items['jsonify/node/%node'] = array(
    'title' => 'Outputs json representation of a node',
    'page callback' => 'jsonify_output',
    'page arguments' => array(2),
    'access callback' => 'node_access',
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK
  );
  $items['jsonify/comment/%jsonify_comment'] = array(
    'title' => 'Outputs json representation of a comment',
    'page callback' => 'jsonify_output',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

/**
 * Load a comment object based on its cid
 */
function jsonify_comment_load($cid) {
  return db_fetch_object(db_query('
    SELECT c.cid, c.nid, c.uid, c.subject, c.comment, c.name AS username, n.title AS node_title 
    FROM {comments} c INNER JOIN {node} n ON c.nid = n.nid 
    WHERE c.status = %d AND c.cid = %d', COMMENT_PUBLISHED, $cid
  ));
}

/**
 * Output json object with the appropriate json headers.
 */ 
function jsonify_output($object) {
  header("Content-Type: application/json");
  echo drupal_to_js($object);
  exit(0);
}
